name: .NET Build

on:
  push:
    branches:
      - master
      - 'release/*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Adjust the version to your project’s target
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Pack Roots.Abstracts
      run: |
        dotnet pack ./Roots.Framework/Roots.Framework.csproj --configuration Release --no-build --output ./artifacts  
        
    - name: Publish Roots Packages
      run: |
         dotnet nuget add source --username ekinbulut --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ekinbulut/index.json"
         dotnet nuget push "./artifacts/*.nupkg"  --api-key ${{ secrets.MY_GITHUB_PAT }} --source "github" --skip-duplicate

